/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables;


import com.veryqy.jooq.Indexes;
import com.veryqy.jooq.Keys;
import com.veryqy.jooq.Public;
import com.veryqy.jooq.tables.records.CommodityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commodity extends TableImpl<CommodityRecord> {

    private static final long serialVersionUID = 730886705;

    /**
     * The reference instance of <code>public.commodity</code>
     */
    public static final Commodity COMMODITY = new Commodity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CommodityRecord> getRecordType() {
        return CommodityRecord.class;
    }

    /**
     * The column <code>public.commodity.id</code>.
     */
    public final TableField<CommodityRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.commodity.col1</code>.
     */
    public final TableField<CommodityRecord, String> COL1 = createField("col1", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col2</code>.
     */
    public final TableField<CommodityRecord, String> COL2 = createField("col2", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col3</code>.
     */
    public final TableField<CommodityRecord, String> COL3 = createField("col3", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col4</code>.
     */
    public final TableField<CommodityRecord, String> COL4 = createField("col4", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col5</code>.
     */
    public final TableField<CommodityRecord, String> COL5 = createField("col5", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col6</code>.
     */
    public final TableField<CommodityRecord, String> COL6 = createField("col6", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col7</code>.
     */
    public final TableField<CommodityRecord, String> COL7 = createField("col7", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col8</code>.
     */
    public final TableField<CommodityRecord, String> COL8 = createField("col8", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col9</code>.
     */
    public final TableField<CommodityRecord, String> COL9 = createField("col9", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.commodity.col10</code>.
     */
    public final TableField<CommodityRecord, String> COL10 = createField("col10", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.commodity</code> table reference
     */
    public Commodity() {
        this(DSL.name("commodity"), null);
    }

    /**
     * Create an aliased <code>public.commodity</code> table reference
     */
    public Commodity(String alias) {
        this(DSL.name(alias), COMMODITY);
    }

    /**
     * Create an aliased <code>public.commodity</code> table reference
     */
    public Commodity(Name alias) {
        this(alias, COMMODITY);
    }

    private Commodity(Name alias, Table<CommodityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Commodity(Name alias, Table<CommodityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMMODITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CommodityRecord> getPrimaryKey() {
        return Keys.COMMODITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CommodityRecord>> getKeys() {
        return Arrays.<UniqueKey<CommodityRecord>>asList(Keys.COMMODITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Commodity as(String alias) {
        return new Commodity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Commodity as(Name alias) {
        return new Commodity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Commodity rename(String name) {
        return new Commodity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Commodity rename(Name name) {
        return new Commodity(name, null);
    }
}
