/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.records;


import com.veryqy.jooq.tables.Commodity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityRecord extends UpdatableRecordImpl<CommodityRecord> implements Record11<String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1679519357;

    /**
     * Setter for <code>public.commodity.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.commodity.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.commodity.category</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.commodity.category</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.commodity.subcategory</code>.
     */
    public void setSubcategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.commodity.subcategory</code>.
     */
    public String getSubcategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.commodity.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.commodity.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.commodity.unit</code>.
     */
    public void setUnit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.commodity.unit</code>.
     */
    public String getUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.commodity.price</code>.
     */
    public void setPrice(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.commodity.price</code>.
     */
    public String getPrice() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.commodity.remark</code>.
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.commodity.remark</code>.
     */
    public String getRemark() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.commodity.subname</code>.
     */
    public void setSubname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.commodity.subname</code>.
     */
    public String getSubname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.commodity.col8</code>.
     */
    public void setCol8(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.commodity.col8</code>.
     */
    public String getCol8() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.commodity.col9</code>.
     */
    public void setCol9(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.commodity.col9</code>.
     */
    public String getCol9() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.commodity.col10</code>.
     */
    public void setCol10(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.commodity.col10</code>.
     */
    public String getCol10() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Commodity.COMMODITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Commodity.COMMODITY.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Commodity.COMMODITY.SUBCATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Commodity.COMMODITY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Commodity.COMMODITY.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Commodity.COMMODITY.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Commodity.COMMODITY.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Commodity.COMMODITY.SUBNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Commodity.COMMODITY.COL8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Commodity.COMMODITY.COL9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Commodity.COMMODITY.COL10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSubcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSubname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCol8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCol9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCol10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSubcategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSubname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCol8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCol9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCol10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value2(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value3(String value) {
        setSubcategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value5(String value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value6(String value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value7(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value8(String value) {
        setSubname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value9(String value) {
        setCol8(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value10(String value) {
        setCol9(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value11(String value) {
        setCol10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityRecord
     */
    public CommodityRecord() {
        super(Commodity.COMMODITY);
    }

    /**
     * Create a detached, initialised CommodityRecord
     */
    public CommodityRecord(String id, String category, String subcategory, String name, String unit, String price, String remark, String subname, String col8, String col9, String col10) {
        super(Commodity.COMMODITY);

        set(0, id);
        set(1, category);
        set(2, subcategory);
        set(3, name);
        set(4, unit);
        set(5, price);
        set(6, remark);
        set(7, subname);
        set(8, col8);
        set(9, col9);
        set(10, col10);
    }
}
