/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.records;


import com.veryqy.jooq.tables.Commodity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityRecord extends UpdatableRecordImpl<CommodityRecord> implements Record11<String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1360687071;

    /**
     * Setter for <code>public.commodity.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.commodity.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.commodity.col1</code>.
     */
    public void setCol1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.commodity.col1</code>.
     */
    public String getCol1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.commodity.col2</code>.
     */
    public void setCol2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.commodity.col2</code>.
     */
    public String getCol2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.commodity.col3</code>.
     */
    public void setCol3(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.commodity.col3</code>.
     */
    public String getCol3() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.commodity.col4</code>.
     */
    public void setCol4(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.commodity.col4</code>.
     */
    public String getCol4() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.commodity.col5</code>.
     */
    public void setCol5(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.commodity.col5</code>.
     */
    public String getCol5() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.commodity.col6</code>.
     */
    public void setCol6(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.commodity.col6</code>.
     */
    public String getCol6() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.commodity.col7</code>.
     */
    public void setCol7(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.commodity.col7</code>.
     */
    public String getCol7() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.commodity.col8</code>.
     */
    public void setCol8(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.commodity.col8</code>.
     */
    public String getCol8() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.commodity.col9</code>.
     */
    public void setCol9(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.commodity.col9</code>.
     */
    public String getCol9() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.commodity.col10</code>.
     */
    public void setCol10(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.commodity.col10</code>.
     */
    public String getCol10() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Commodity.COMMODITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Commodity.COMMODITY.COL1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Commodity.COMMODITY.COL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Commodity.COMMODITY.COL3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Commodity.COMMODITY.COL4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Commodity.COMMODITY.COL5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Commodity.COMMODITY.COL6;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Commodity.COMMODITY.COL7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Commodity.COMMODITY.COL8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Commodity.COMMODITY.COL9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Commodity.COMMODITY.COL10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCol1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCol2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCol3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCol4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCol5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCol6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCol7();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCol8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCol9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCol10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCol1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCol2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCol3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCol4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCol5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCol6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCol7();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCol8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCol9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCol10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value2(String value) {
        setCol1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value3(String value) {
        setCol2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value4(String value) {
        setCol3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value5(String value) {
        setCol4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value6(String value) {
        setCol5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value7(String value) {
        setCol6(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value8(String value) {
        setCol7(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value9(String value) {
        setCol8(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value10(String value) {
        setCol9(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord value11(String value) {
        setCol10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommodityRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommodityRecord
     */
    public CommodityRecord() {
        super(Commodity.COMMODITY);
    }

    /**
     * Create a detached, initialised CommodityRecord
     */
    public CommodityRecord(String id, String col1, String col2, String col3, String col4, String col5, String col6, String col7, String col8, String col9, String col10) {
        super(Commodity.COMMODITY);

        set(0, id);
        set(1, col1);
        set(2, col2);
        set(3, col3);
        set(4, col4);
        set(5, col5);
        set(6, col6);
        set(7, col7);
        set(8, col8);
        set(9, col9);
        set(10, col10);
    }
}
