/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.records;


import com.veryqy.jooq.tables.Contractor;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractorRecord extends UpdatableRecordImpl<ContractorRecord> implements Record8<String, String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = -1793146805;

    /**
     * Setter for <code>public.contractor.agreement_id</code>.
     */
    public void setAgreementId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.contractor.agreement_id</code>.
     */
    public String getAgreementId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.contractor.id</code>.
     */
    public void setId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.contractor.id</code>.
     */
    public String getId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contractor.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.contractor.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contractor.person_name</code>.
     */
    public void setPersonName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.contractor.person_name</code>.
     */
    public String getPersonName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.contractor.person_idno</code>.
     */
    public void setPersonIdno(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.contractor.person_idno</code>.
     */
    public String getPersonIdno() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.contractor.josn</code>.
     */
    public void setJosn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.contractor.josn</code>.
     */
    public String getJosn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.contractor.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.contractor.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.contractor.create_by</code>.
     */
    public void setCreateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.contractor.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Contractor.CONTRACTOR.AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Contractor.CONTRACTOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contractor.CONTRACTOR.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Contractor.CONTRACTOR.PERSON_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Contractor.CONTRACTOR.PERSON_IDNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Contractor.CONTRACTOR.JOSN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Contractor.CONTRACTOR.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Contractor.CONTRACTOR.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPersonIdno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getJosn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPersonName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPersonIdno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getJosn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value1(String value) {
        setAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value2(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value4(String value) {
        setPersonName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value5(String value) {
        setPersonIdno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value6(String value) {
        setJosn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value7(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord value8(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractorRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractorRecord
     */
    public ContractorRecord() {
        super(Contractor.CONTRACTOR);
    }

    /**
     * Create a detached, initialised ContractorRecord
     */
    public ContractorRecord(String agreementId, String id, String name, String personName, String personIdno, String josn, Timestamp createDate, String createBy) {
        super(Contractor.CONTRACTOR);

        set(0, agreementId);
        set(1, id);
        set(2, name);
        set(3, personName);
        set(4, personIdno);
        set(5, josn);
        set(6, createDate);
        set(7, createBy);
    }
}
