/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq;


import com.veryqy.jooq.tables.Commodity;
import com.veryqy.jooq.tables.Contractor;
import com.veryqy.jooq.tables.Order;
import com.veryqy.jooq.tables.Row;
import com.veryqy.jooq.tables.User;
import com.veryqy.jooq.tables.records.CommodityRecord;
import com.veryqy.jooq.tables.records.ContractorRecord;
import com.veryqy.jooq.tables.records.OrderRecord;
import com.veryqy.jooq.tables.records.RowRecord;
import com.veryqy.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommodityRecord> COMMODITY_PKEY = UniqueKeys0.COMMODITY_PKEY;
    public static final UniqueKey<ContractorRecord> CONTRACTOR_PKEY = UniqueKeys0.CONTRACTOR_PKEY;
    public static final UniqueKey<OrderRecord> ORDER_PKEY = UniqueKeys0.ORDER_PKEY;
    public static final UniqueKey<RowRecord> ROW_PKEY = UniqueKeys0.ROW_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CommodityRecord> COMMODITY_PKEY = Internal.createUniqueKey(Commodity.COMMODITY, "commodity_pkey", Commodity.COMMODITY.ID);
        public static final UniqueKey<ContractorRecord> CONTRACTOR_PKEY = Internal.createUniqueKey(Contractor.CONTRACTOR, "contractor_pkey", Contractor.CONTRACTOR.ID);
        public static final UniqueKey<OrderRecord> ORDER_PKEY = Internal.createUniqueKey(Order.ORDER, "Order_pkey", Order.ORDER.ID);
        public static final UniqueKey<RowRecord> ROW_PKEY = Internal.createUniqueKey(Row.ROW, "row_pkey", Row.ROW.ID);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", User.USER.ID);
    }
}
