/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq;


import com.veryqy.jooq.tables.Commodity;
import com.veryqy.jooq.tables.Contractor;
import com.veryqy.jooq.tables.Order;
import com.veryqy.jooq.tables.Row;
import com.veryqy.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2090813722;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.commodity</code>.
     */
    public final Commodity COMMODITY = com.veryqy.jooq.tables.Commodity.COMMODITY;

    /**
     * The table <code>public.contractor</code>.
     */
    public final Contractor CONTRACTOR = com.veryqy.jooq.tables.Contractor.CONTRACTOR;

    /**
     * The table <code>public.order</code>.
     */
    public final Order ORDER = com.veryqy.jooq.tables.Order.ORDER;

    /**
     * The table <code>public.row</code>.
     */
    public final Row ROW = com.veryqy.jooq.tables.Row.ROW;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = com.veryqy.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Commodity.COMMODITY,
            Contractor.CONTRACTOR,
            Order.ORDER,
            Row.ROW,
            User.USER);
    }
}
