/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commodity implements Serializable {

    private static final long serialVersionUID = -774400671;

    private String id;
    private String category;
    private String subcategory;
    private String name;
    private String unit;
    private String price;
    private String remark;
    private String subname;
    private String col8;
    private String col9;
    private String col10;

    public Commodity() {}

    public Commodity(Commodity value) {
        this.id = value.id;
        this.category = value.category;
        this.subcategory = value.subcategory;
        this.name = value.name;
        this.unit = value.unit;
        this.price = value.price;
        this.remark = value.remark;
        this.subname = value.subname;
        this.col8 = value.col8;
        this.col9 = value.col9;
        this.col10 = value.col10;
    }

    public Commodity(
        String id,
        String category,
        String subcategory,
        String name,
        String unit,
        String price,
        String remark,
        String subname,
        String col8,
        String col9,
        String col10
    ) {
        this.id = id;
        this.category = category;
        this.subcategory = subcategory;
        this.name = name;
        this.unit = unit;
        this.price = price;
        this.remark = remark;
        this.subname = subname;
        this.col8 = col8;
        this.col9 = col9;
        this.col10 = col10;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getSubcategory() {
        return this.subcategory;
    }

    public void setSubcategory(String subcategory) {
        this.subcategory = subcategory;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getSubname() {
        return this.subname;
    }

    public void setSubname(String subname) {
        this.subname = subname;
    }

    public String getCol8() {
        return this.col8;
    }

    public void setCol8(String col8) {
        this.col8 = col8;
    }

    public String getCol9() {
        return this.col9;
    }

    public void setCol9(String col9) {
        this.col9 = col9;
    }

    public String getCol10() {
        return this.col10;
    }

    public void setCol10(String col10) {
        this.col10 = col10;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Commodity (");

        sb.append(id);
        sb.append(", ").append(category);
        sb.append(", ").append(subcategory);
        sb.append(", ").append(name);
        sb.append(", ").append(unit);
        sb.append(", ").append(price);
        sb.append(", ").append(remark);
        sb.append(", ").append(subname);
        sb.append(", ").append(col8);
        sb.append(", ").append(col9);
        sb.append(", ").append(col10);

        sb.append(")");
        return sb.toString();
    }
}
