/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Commodity implements Serializable {

    private static final long serialVersionUID = -85687246;

    private String id;
    private String col1;
    private String col2;
    private String col3;
    private String col4;
    private String col5;
    private String col6;
    private String col7;
    private String col8;
    private String col9;
    private String col10;

    public Commodity() {}

    public Commodity(Commodity value) {
        this.id = value.id;
        this.col1 = value.col1;
        this.col2 = value.col2;
        this.col3 = value.col3;
        this.col4 = value.col4;
        this.col5 = value.col5;
        this.col6 = value.col6;
        this.col7 = value.col7;
        this.col8 = value.col8;
        this.col9 = value.col9;
        this.col10 = value.col10;
    }

    public Commodity(
        String id,
        String col1,
        String col2,
        String col3,
        String col4,
        String col5,
        String col6,
        String col7,
        String col8,
        String col9,
        String col10
    ) {
        this.id = id;
        this.col1 = col1;
        this.col2 = col2;
        this.col3 = col3;
        this.col4 = col4;
        this.col5 = col5;
        this.col6 = col6;
        this.col7 = col7;
        this.col8 = col8;
        this.col9 = col9;
        this.col10 = col10;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCol1() {
        return this.col1;
    }

    public void setCol1(String col1) {
        this.col1 = col1;
    }

    public String getCol2() {
        return this.col2;
    }

    public void setCol2(String col2) {
        this.col2 = col2;
    }

    public String getCol3() {
        return this.col3;
    }

    public void setCol3(String col3) {
        this.col3 = col3;
    }

    public String getCol4() {
        return this.col4;
    }

    public void setCol4(String col4) {
        this.col4 = col4;
    }

    public String getCol5() {
        return this.col5;
    }

    public void setCol5(String col5) {
        this.col5 = col5;
    }

    public String getCol6() {
        return this.col6;
    }

    public void setCol6(String col6) {
        this.col6 = col6;
    }

    public String getCol7() {
        return this.col7;
    }

    public void setCol7(String col7) {
        this.col7 = col7;
    }

    public String getCol8() {
        return this.col8;
    }

    public void setCol8(String col8) {
        this.col8 = col8;
    }

    public String getCol9() {
        return this.col9;
    }

    public void setCol9(String col9) {
        this.col9 = col9;
    }

    public String getCol10() {
        return this.col10;
    }

    public void setCol10(String col10) {
        this.col10 = col10;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Commodity (");

        sb.append(id);
        sb.append(", ").append(col1);
        sb.append(", ").append(col2);
        sb.append(", ").append(col3);
        sb.append(", ").append(col4);
        sb.append(", ").append(col5);
        sb.append(", ").append(col6);
        sb.append(", ").append(col7);
        sb.append(", ").append(col8);
        sb.append(", ").append(col9);
        sb.append(", ").append(col10);

        sb.append(")");
        return sb.toString();
    }
}
