/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contractor implements Serializable {

    private static final long serialVersionUID = 1195382934;

    private String    agreementId;
    private String    id;
    private String    name;
    private String    personName;
    private String    personIdno;
    private String    josn;
    private Timestamp createDate;
    private String    createBy;

    public Contractor() {}

    public Contractor(Contractor value) {
        this.agreementId = value.agreementId;
        this.id = value.id;
        this.name = value.name;
        this.personName = value.personName;
        this.personIdno = value.personIdno;
        this.josn = value.josn;
        this.createDate = value.createDate;
        this.createBy = value.createBy;
    }

    public Contractor(
        String    agreementId,
        String    id,
        String    name,
        String    personName,
        String    personIdno,
        String    josn,
        Timestamp createDate,
        String    createBy
    ) {
        this.agreementId = agreementId;
        this.id = id;
        this.name = name;
        this.personName = personName;
        this.personIdno = personIdno;
        this.josn = josn;
        this.createDate = createDate;
        this.createBy = createBy;
    }

    public String getAgreementId() {
        return this.agreementId;
    }

    public void setAgreementId(String agreementId) {
        this.agreementId = agreementId;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPersonName() {
        return this.personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getPersonIdno() {
        return this.personIdno;
    }

    public void setPersonIdno(String personIdno) {
        this.personIdno = personIdno;
    }

    public String getJosn() {
        return this.josn;
    }

    public void setJosn(String josn) {
        this.josn = josn;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contractor (");

        sb.append(agreementId);
        sb.append(", ").append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(personName);
        sb.append(", ").append(personIdno);
        sb.append(", ").append(josn);
        sb.append(", ").append(createDate);
        sb.append(", ").append(createBy);

        sb.append(")");
        return sb.toString();
    }
}
