/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1243860488;

    private String id;
    private String title;
    private String contractorId;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.title = value.title;
        this.contractorId = value.contractorId;
    }

    public Order(
        String id,
        String title,
        String contractorId
    ) {
        this.id = id;
        this.title = title;
        this.contractorId = contractorId;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContractorId() {
        return this.contractorId;
    }

    public void setContractorId(String contractorId) {
        this.contractorId = contractorId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(contractorId);

        sb.append(")");
        return sb.toString();
    }
}
