/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.daos;


import com.veryqy.jooq.tables.Commodity;
import com.veryqy.jooq.tables.records.CommodityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityDao extends DAOImpl<CommodityRecord, com.veryqy.jooq.tables.pojos.Commodity, String> {

    /**
     * Create a new CommodityDao without any configuration
     */
    public CommodityDao() {
        super(Commodity.COMMODITY, com.veryqy.jooq.tables.pojos.Commodity.class);
    }

    /**
     * Create a new CommodityDao with an attached configuration
     */
    public CommodityDao(Configuration configuration) {
        super(Commodity.COMMODITY, com.veryqy.jooq.tables.pojos.Commodity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.veryqy.jooq.tables.pojos.Commodity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchById(String... values) {
        return fetch(Commodity.COMMODITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.veryqy.jooq.tables.pojos.Commodity fetchOneById(String value) {
        return fetchOne(Commodity.COMMODITY.ID, value);
    }

    /**
     * Fetch records that have <code>col1 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol1(String... values) {
        return fetch(Commodity.COMMODITY.COL1, values);
    }

    /**
     * Fetch records that have <code>col2 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol2(String... values) {
        return fetch(Commodity.COMMODITY.COL2, values);
    }

    /**
     * Fetch records that have <code>col3 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol3(String... values) {
        return fetch(Commodity.COMMODITY.COL3, values);
    }

    /**
     * Fetch records that have <code>col4 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol4(String... values) {
        return fetch(Commodity.COMMODITY.COL4, values);
    }

    /**
     * Fetch records that have <code>col5 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol5(String... values) {
        return fetch(Commodity.COMMODITY.COL5, values);
    }

    /**
     * Fetch records that have <code>col6 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol6(String... values) {
        return fetch(Commodity.COMMODITY.COL6, values);
    }

    /**
     * Fetch records that have <code>col7 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol7(String... values) {
        return fetch(Commodity.COMMODITY.COL7, values);
    }

    /**
     * Fetch records that have <code>col8 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol8(String... values) {
        return fetch(Commodity.COMMODITY.COL8, values);
    }

    /**
     * Fetch records that have <code>col9 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol9(String... values) {
        return fetch(Commodity.COMMODITY.COL9, values);
    }

    /**
     * Fetch records that have <code>col10 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol10(String... values) {
        return fetch(Commodity.COMMODITY.COL10, values);
    }
}
