/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.daos;


import com.veryqy.jooq.tables.Commodity;
import com.veryqy.jooq.tables.records.CommodityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommodityDao extends DAOImpl<CommodityRecord, com.veryqy.jooq.tables.pojos.Commodity, String> {

    /**
     * Create a new CommodityDao without any configuration
     */
    public CommodityDao() {
        super(Commodity.COMMODITY, com.veryqy.jooq.tables.pojos.Commodity.class);
    }

    /**
     * Create a new CommodityDao with an attached configuration
     */
    public CommodityDao(Configuration configuration) {
        super(Commodity.COMMODITY, com.veryqy.jooq.tables.pojos.Commodity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.veryqy.jooq.tables.pojos.Commodity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchById(String... values) {
        return fetch(Commodity.COMMODITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.veryqy.jooq.tables.pojos.Commodity fetchOneById(String value) {
        return fetchOne(Commodity.COMMODITY.ID, value);
    }

    /**
     * Fetch records that have <code>category IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCategory(String... values) {
        return fetch(Commodity.COMMODITY.CATEGORY, values);
    }

    /**
     * Fetch records that have <code>subcategory IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchBySubcategory(String... values) {
        return fetch(Commodity.COMMODITY.SUBCATEGORY, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByName(String... values) {
        return fetch(Commodity.COMMODITY.NAME, values);
    }

    /**
     * Fetch records that have <code>unit IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByUnit(String... values) {
        return fetch(Commodity.COMMODITY.UNIT, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByPrice(String... values) {
        return fetch(Commodity.COMMODITY.PRICE, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByRemark(String... values) {
        return fetch(Commodity.COMMODITY.REMARK, values);
    }

    /**
     * Fetch records that have <code>subname IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchBySubname(String... values) {
        return fetch(Commodity.COMMODITY.SUBNAME, values);
    }

    /**
     * Fetch records that have <code>col8 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol8(String... values) {
        return fetch(Commodity.COMMODITY.COL8, values);
    }

    /**
     * Fetch records that have <code>col9 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol9(String... values) {
        return fetch(Commodity.COMMODITY.COL9, values);
    }

    /**
     * Fetch records that have <code>col10 IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Commodity> fetchByCol10(String... values) {
        return fetch(Commodity.COMMODITY.COL10, values);
    }
}
