/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.daos;


import com.veryqy.jooq.tables.Contractor;
import com.veryqy.jooq.tables.records.ContractorRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractorDao extends DAOImpl<ContractorRecord, com.veryqy.jooq.tables.pojos.Contractor, String> {

    /**
     * Create a new ContractorDao without any configuration
     */
    public ContractorDao() {
        super(Contractor.CONTRACTOR, com.veryqy.jooq.tables.pojos.Contractor.class);
    }

    /**
     * Create a new ContractorDao with an attached configuration
     */
    public ContractorDao(Configuration configuration) {
        super(Contractor.CONTRACTOR, com.veryqy.jooq.tables.pojos.Contractor.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.veryqy.jooq.tables.pojos.Contractor object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>agreement_id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByAgreementId(String... values) {
        return fetch(Contractor.CONTRACTOR.AGREEMENT_ID, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchById(String... values) {
        return fetch(Contractor.CONTRACTOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.veryqy.jooq.tables.pojos.Contractor fetchOneById(String value) {
        return fetchOne(Contractor.CONTRACTOR.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByName(String... values) {
        return fetch(Contractor.CONTRACTOR.NAME, values);
    }

    /**
     * Fetch records that have <code>person_name IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByPersonName(String... values) {
        return fetch(Contractor.CONTRACTOR.PERSON_NAME, values);
    }

    /**
     * Fetch records that have <code>person_idno IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByPersonIdno(String... values) {
        return fetch(Contractor.CONTRACTOR.PERSON_IDNO, values);
    }

    /**
     * Fetch records that have <code>josn IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByJosn(String... values) {
        return fetch(Contractor.CONTRACTOR.JOSN, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByCreateDate(Timestamp... values) {
        return fetch(Contractor.CONTRACTOR.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Contractor> fetchByCreateBy(String... values) {
        return fetch(Contractor.CONTRACTOR.CREATE_BY, values);
    }
}
