/*
 * This file is generated by jOOQ.
*/
package com.veryqy.jooq.tables.daos;


import com.veryqy.jooq.tables.Order;
import com.veryqy.jooq.tables.records.OrderRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDao extends DAOImpl<OrderRecord, com.veryqy.jooq.tables.pojos.Order, String> {

    /**
     * Create a new OrderDao without any configuration
     */
    public OrderDao() {
        super(Order.ORDER, com.veryqy.jooq.tables.pojos.Order.class);
    }

    /**
     * Create a new OrderDao with an attached configuration
     */
    public OrderDao(Configuration configuration) {
        super(Order.ORDER, com.veryqy.jooq.tables.pojos.Order.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.veryqy.jooq.tables.pojos.Order object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Order> fetchById(String... values) {
        return fetch(Order.ORDER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.veryqy.jooq.tables.pojos.Order fetchOneById(String value) {
        return fetchOne(Order.ORDER.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Order> fetchByTitle(String... values) {
        return fetch(Order.ORDER.TITLE, values);
    }

    /**
     * Fetch records that have <code>contractor_id IN (values)</code>
     */
    public List<com.veryqy.jooq.tables.pojos.Order> fetchByContractorId(String... values) {
        return fetch(Order.ORDER.CONTRACTOR_ID, values);
    }
}
